# Generated by Django 4.0.6 on 2022-07-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_service_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='max_order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='min_order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
