# Generated by Django 4.0.6 on 2022-07-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_service_max_order_alter_service_min_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='max_order',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='min_order',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='rate',
            field=models.BigIntegerField(),
        ),
    ]
