# Generated by Django 4.0.6 on 2022-07-17 00:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_service_max_order_alter_service_min_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(blank='True', default='', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
