# Generated by Django 4.0.6 on 2022-07-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_service_description_alter_service_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=500),
        ),
    ]
